### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by yafengwen** [Illumina/Cyrius#11]
Hi, 

I have BAM and BAI files for a focused pharmacogene panel, including CYP2D6, generated from a clinical lab following in-house pipeline. I performed the following analysis with Python 3.8.3 on linux system: 

```bash 
git clone https://github.com/Illumina/Cyrius.git

python3 star_caller.py --manifest /path/to/bam/file.bam \
    		       --genome 37 \
    		       --prefix file \
    		       --outDir /path/to/work/directory/ \
    		       --threads 1
```

But I got the following error: 
```
Traceback (most recent call last):
  File "bin/Cyrius/star_caller.py", line 562, in <module>
    main()
  File "bin/Cyrius/star_caller.py", line 513, in main
    for line in read_manifest:
  File "/panfs/roc/msisoft/anaconda/miniconda3_4.8.3-jupyter/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```
Input files or the Cyrius folder are not in gzipped files.  Any suggestions?

Thank you.

**Comment by xiao-chen-xc** [comment]
Hi Ya-Feng,

The manifest does not take the BAM file directly. Instead it is a text file that lists the path to a BAM in each line (it can have multiple lines, one BAM per line).

Also you mentioned you have data from a gene panel. Is it targeted sequencing data? Cyrius works for WGS data only.

Thanks,
Xiao

**Comment by yafengwen** [comment]
Hi Xiao, 

Thank you so much for the quick reply! Sorry that I missed the instruction on constructing the manifest textfile. 

The files I have are indeed targeted sequencing data. Now I can why WGS data is needed as you responded in #9. I will use other tools for the genotype calling for CYP2D6 and other pharmacogenes then. 

Thank you,
Ya-Feng
