### ISSUE TITLE
Sample specific error

### ISSUE THREAD

**Issue by holtjma** [Illumina/Cyrius#12]
Hello,

We've been using Cyrius-1.0 for a while and came across and error recently.  I updated to v1.1 and the error is persisting.
The command we're using is:
```
python3 -u /gpfs/gpfs1/home/jholt/githubDL/Cyrius-1.1/star_caller.py             \
    --manifest {redacted}/cyrius-1.0/HALB3003261.txt             \
    --genome 38             \
    --outDir {redacted}/cyrius-1.0             \
    --prefix HALB3003261             \
    --threads 1
```
And the output is as follows:
```
INFO:root:Processing sample HALB3003261 at 2021-04-28 08:55:21.589540
Traceback (most recent call last):
  File "/gpfs/gpfs1/home/jholt/githubDL/Cyrius-1.1/star_caller.py", line 560, in <module>
    main()
  File "/gpfs/gpfs1/home/jholt/githubDL/Cyrius-1.1/star_caller.py", line 528, in main
    bam_name, call_parameters, threads, count_file, reference_fasta
  File "/gpfs/gpfs1/home/jholt/githubDL/Cyrius-1.1/star_caller.py", line 403, in d6_star_caller
    if ";" in final_star_allele_call:
TypeError: argument of type 'NoneType' is not iterable
```

Let me know if you need any additional information from me!

**Comment by xiao-chen-xc** [comment]
Hi @holtjma 

Probably one sample that has a rare and complicated genotype caused the error. Could you try the latest master branch and see if it would work (the sample would probably get a no-call but hopefully there is no more program error)?

Thanks,
Xiao

**Comment by holtjma** [comment]
Yes, that did stop the crash and it generated a no-call.  Any ideas on figuring out the no-call?

**Comment by xiao-chen-xc** [comment]
Would it be possible to send me the json output file for that sample?

**Comment by holtjma** [comment]
Yep, I sent them to your email (I think it's the correct address from a previous issue).

**Comment by xiao-chen-xc** [comment]
Hi Matt,

Could you check if the latest master branch fix this sample? 

Thanks,
Xiao

**Comment by holtjma** [comment]
Yes, it's reporting `*13+*4/*9` now, which I think is equivalent to what you indicated via email.  If so, I think you can close this one.  Will this be in a released version soon?

**Comment by xiao-chen-xc** [comment]
Great. Just made a new release.
