### ISSUE TITLE
interpreting d67_snp_* fields in json output

### ISSUE THREAD

**Issue by mgonzalezporta** [Illumina/Cyrius#13]
Hi Xiao,

We're trying to reproduce these 2 figures from the Cyrius manuscript:

![image](https://user-images.githubusercontent.com/1401387/130399081-32638c29-a4c7-4640-8b11-259a0f5f9fba.png)

We've identified the relevant fields from the json output to be used, namely `d67_snp_call` and `d67_snp_raw` for panel B, and `Variants_called` for panel C.

Since the `d67_snp_*` fields are not annotated with variant information, we wanted to confirm that we're interpreting them correctly. Are we OK to assume that each differentiated variant appears in the same order as in the bundled annotation files (https://github.com/Illumina/Cyrius/blob/master/data/CYP2D6_SNP_38.txt)?

Thanks in advance!

**Comment by xiao-chen-xc** [comment]
Hi @mgonzalezporta 

Yes that is correct. The order is the same as in the CYP2D6_SNP_*.txt resource file.

Thanks,
Xiao

**Comment by mgonzalezporta** [comment]
Thanks!
