### ISSUE TITLE
Alternate and Reference Read Count Output Format

### ISSUE THREAD

**Issue by benediktusrayo-nala** [Illumina/Cyrius#14]
I was running Cyrius to test its performance on the NA12878 data and noticed that one of the outputs from your JSON file is the field "Variant_raw_count". For each entry, subsequent to the position and mutation information are I believe the alternate allele read count and reference allele read count. Wouldn't the convention typically be the reference allele count followed by the alternate allele count? Or is that already how you define your output?

Thank you

**Comment by xiao-chen-xc** [comment]
Hi @benediktusrayo-nala 

Yes the numbers are variant read count and reference read count. Feel free to parse the json file to get these numbers and use them in a way you like.  

Thanks,
Xiao
