### ISSUE TITLE
Calling on Cyrius test data

### ISSUE THREAD

**Issue by benediktusrayo-nala** [Illumina/Cyrius#16]
I was trying to run your test data from this Github (Cyrius/depth_calling/tests/test_data/NA12878.bam) using this following command: 

`python3 star_caller.py --manifest cyp2d6_GRCh37_manifest.txt --genome 37 --prefix cyp2d6_GRCh37_NA12878 --outDir cyrius_run_and_visualization --threads 4 `

But it gave me these errors:
```
1. RuntimeWarning: Mean of empty slice.
2. RuntimeWarning: invalid value encountered in double_scalars  ret = ret.dtype.type(ret / rcount)
3. RuntimeWarning: invalid value encountered in true_divide  y_counts = y_counts / np.median(y_counts)
```

Since I'm using your test data, I'm unsure how it's giving me an error. Do you happen to know if I'm doing anything wrong?

**Comment by xiao-chen-xc** [comment]
Hi @benediktusrayo-nala 

The test data is not a WGS bam, so Cyrius won't work if you run it from the command line. Instead the test bam is used for unit testing. You can run all tests by typing "pytest -l" from the Cyrius directory. You can also test a real WGS bam from the command line - there should be plenty of publicly available ones. Let me know if this is not clear or you run into any problem.

Thanks,
Xiao
