### ISSUE TITLE
Minor bug in target variants for GRch37

### ISSUE THREAD

**Issue by benz888-tech** [Illumina/Cyrius#17]
Hello @xiao-chen-xc,

I was running your program with GRch37 data and found a minor bug. I think you put the wrong position in the variant_name from file Cyrius/data/CYP2D6_target_variant_37.txt. For example, `variant_name : g.42126611C>G` where the real position should be `42522613`. I also found the same issue in  Cyrius/data/CYP2D6_target_variant_19.txt.  

Thanks !

Best regards
Benz

**Comment by xiao-chen-xc** [comment]
Hi Benz,

The variant name is based on the coordinate of the variant on HG38. This way we refer to a variant consistently regardless of the reference genome. It wouldn't affect the star allele calling because the star alleles are defined by variants named in this way. 

Thanks,
Xiao
