### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by neoscreen** [Illumina/Cyrius#23]
Hi,
Is there a newer version covering more genes, other than CYP2D6?
I found a related newsletter from Illumina.

Thank you

**Comment by xiao-chen-xc** [comment]
Hi @neoscreen

Sorry about my late reply! We will not be adding new genes to Cyrius in this git repo. However, Illumina is planning to release a star allele caller for a set of important PGx genes in DRAGEN. We also have plans to add Cyrius for CYP2D6 as well as other genes to ICA (Illumina Connected Analytics), which is Illumina's cloud based software platform.

Thanks,
Xiao
