### ISSUE TITLE
WGS only?

### ISSUE THREAD

**Issue by JARM89** [Illumina/Cyrius#26]
Have anyone tested Cyrius with data from a chip or single sequenced gen? Thank you in advance.

**Comment by xiao-chen-xc** [comment]
Hi @JARM89 Cyrius is designed for WGS data only. The copy number calling algorithm uses assumptions of WGS and will need modifications to work for other types of data.

**Comment by JARM89** [comment]
> 

Thank you for the information.

**Comment by BTHermann** [comment]
Hi @xiao-chen-xc ,
can those modifications be done by specifying other reference regions in the genome? Assuming that refernce regions for CN determination are specified in **CYP2D6_region_38.bed** ( _19 or _37, respectivley), is it possible to customize this file accoding to a utilized (targeted) panel? 

Man thanks in advance for your help.

**Comment by xiao-chen-xc** [comment]
Hi @BTHermann, Cyrius assumes that the coverage is uniform across the regions specified in the bed file so it only does simple normalization and GC correction. For targeted data, there is more variation across the panel, so one needs to add the logic to normalize depth based on depth patterns specific to the panel.

**Comment by xiao-chen-xc** [comment]
For WGS, they are there just to provide some median normalization and GC normalization, and they are simply some regions of the genome that have stable coverage across samples. If you want to add your own normalization method for targeted data, it really depends on your own need, i.e. you can decide the number and size of regions that would allow best normalization results.

**Comment by BTHermann** [comment]
Allright, thank you for your feedback! It is much appreciated.
