### ISSUE TITLE
fetch called on bamfile without index?

### ISSUE THREAD

**Issue by yebinkim17** [Illumina/Cyrius#29]
Hi, I enjoyed your article very much. Now I am trying to apply Cyrius software tool on analyzing CYP2D6 gene for my research. However, while I was trying to run the tool, I faced an error that I cannot figure out.

The command I entered is as following : 

**python3 star_caller.py --manifest manifest.txt --genome 38 --prefix test --outDir ./output/**

This is the error I see:

**ValueError: fetch called on bamfile without index**
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/111806940/193705661-7c8ef0af-c84e-4bc1-bbb7-693db9b1da8d.png">

I don't think I need bam.bai file, but the error says that "could not retrieve index for bam file".  (In the manifest.txt file, there is only one line of the bam file path.) So, I am wondering how I can troubleshoot this issue.

Also, can we use a sliced WGS bam file as an input? For example, ch22.bam.

Thank you very much.

**Comment by xiao-chen-xc** [comment]
Hi @yebinkim17, no need to put a bai file path in the manifest, but there should be a bai file in the same directory as the bam file.
If you want to slice a WGS bam, please slice the regions specified in https://github.com/Illumina/Cyrius/blob/master/data/CYP2D6_region_38.bed

**Comment by yebinkim17** [comment]
Thank you for your response. It resolved the issue.
