### ISSUE TITLE
Unknown variants?

### ISSUE THREAD

**Issue by yebinkim17** [Illumina/Cyrius#31]
Hi, I appreciate for your kind response for the previous issue I submitted last time! :) I do have one more question about the result in your article.

I am practicing finding rare variants in multi-allelic genes. And I found out that there were 26 samples that had variants calls that did not match any of the known star alleles out of 2504 1kGP samples after running Cyrius. If it's available, can I get the sample id of the 26 samples? 

Thank you very much.

**Comment by xiao-chen-xc** [comment]
Hi @yebinkim17 the sample ids can be found in the supplementary tables (Table S5) of the paper (https://www.nature.com/articles/s41397-020-00205-5#Sec11).

**Comment by yebinkim17** [comment]
Thank you!
