### ISSUE TITLE
Questions about odd genotypes

### ISSUE THREAD

**Issue by anh151** [Illumina/Cyrius#32]
I am using the latest version of Cyrius. Initial feedback I want to give is that Cyrius is very easy to install and use. I really appreciate that. Some tools can be a bear to get setup and running. 

I have a few of samples where I have some odd genotypes that I'm not sure how to interpret.

1. *1_*1_*13 - I understand that this signifies that this is a `Not_assigned_to_haplotypes` scenario. But I'm not following what the possibilities would be. *1/*1+*13, shouldn't that just be *1/*13? or *1+*1/*13, shouldn't that just be *1x2/*13?
2. *1/*68+*68+*68+*4 and another one that is *1/*68+*68+*68+*68+*4 - why are there so many *68s? What does this mean?
3. *41/*4.013+*4 - is this the equivalent of *41/*4x2?

Thanks

**Comment by xiao-chen-xc** [comment]
Hi @anh151 

1. Cyrius finds three copies of CYP2D6, *1, *1 and *13, and it doesn't know which two of them are on the same chromosome. *1/*1+*13 is not *1/*13. The former is three copies and the latter is two copies. *1+*1/*13 is equivalent to *1x2/*13.

2. Each *68 is an additional copy of the gene. It's a fusion between CYP2D6 and CYP2D7. It is created by sequence duplication.

3. Functionally *4.013 is a suballele of *4 so you can consider it equivalent to *4. We report *4.013 to reflect the mechanism that it is a gene fusion between CYP2D6 and CYP2D7, while by *4x2 you are indicating that this is a full gene duplication. The two scenarios are different.

Thanks,
Xiao

**Comment by anh151** [comment]
Hi Xiao,
Thanks for the responses.

1. Given a hypothetical scenario where *2 and *3 are each defined by a unique variant. If Cyrius reports a genotype as `*1/*2+*3`, does this indicate that both *2 and *3 were found on the same single copy of the gene or does this mean that the sample has two copies of CYP2D6 on the same chromomsome, the first copy carrying the *2 allele and the second copy carrying the *3 allele? How does Cyrius differentiate between these two scenarios?
2. Just to be clear on this one. Given the example `*1/*68+*68+*68+*68+*4`. This indicates that 6 total gene/hybrid gene copies were detected in the sample. 1 copy carrying *1, 1 copy carrying *4, and 4 copies of the *68 hybrid gene. 
3. You're right. I missed that. Thanks for clarifying. 

Thanks,
Andrew

**Comment by xiao-chen-xc** [comment]
1. It's the latter scenario. Each star allele is a copy of the gene. Cyrius first detects the total copy number of the gene and then figures out the star allele assignment of each copy. If the variants defining *2 and *3 are both found in the same single copy of the gene, then this copy should be neither *2 or *3 - it must be some other star allele.
2. That's correct.

**Comment by anh151** [comment]
Perfect. Thanks for the quick responses.
