### ISSUE TITLE
snp_count.py:127: UserWarning, haplotype.py:70: UserWarning

### ISSUE THREAD

**Issue by timsanford** [Illumina/Cyrius#36]
When running Cyrius on 5 wgs CRAM samples (all listed in a manifest text file), I received the following error after message that the first sample was processing:

Cyrius/depth_calling/snp_count.py:127: UserWarning: multiple_iterators not implemented for CRAM
   ignore_orphan = False,
Cyrius/depth_calling/haplotype.py:70: UserWarning: multiple_iterators not implemented for CRAM
   ignore_orphan = False

Though I received this message, the output tsv and json files appear to show that Cyrius ran correctly. Can you help me understand these error messages and if anything needs to be fixed?

Thank you!

**Comment by xiao-chen-xc** [comment]
Hi @timsanford, this warning should not impact the program. The results can be trusted.
