### ISSUE TITLE
Is there a way to use just a part of cram/bam file to get not-None Cyrius result?

### ISSUE THREAD

**Issue by muzic194** [Illumina/Cyrius#5]
Is there a way to use just a part of cram/bam file to get not-None Cyrius result?

I used sample NA19239 from 1000-genomes, aligned to hg38 in .cram format. 

```
wget ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR323/ERR3239454/NA19239.final.cram
wget ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR323/ERR3239454/NA19239.final.cram.crai
```
Result of Cyrius: 
```Sample    Genotype    Filter
NA19239.final    *15/*17    PASS
```

When I extracted only chr22 using samtools view:
``samtools view -C NA19239.final.cram chr22 > NA19239_chr22.cram``
``samtools index NA19239_chr22.cram``

Result of Cyrius: 

```
Sample	Genotype	Filter
NA19239_chr22	None	None
```
Thanks

**Comment by cariaso** [comment]
Note that
https://github.com/Illumina/Cyrius/pull/6
should offer a significant improvement for your use case

**Comment by xiao-chen-xc** [comment]
Hi @muzic194, Cyrius uses some other regions of the genome for depth normalization. You can extract a bam using [https://github.com/Illumina/Cyrius/blob/master/data/CYP2D6_region_38.bed](url) and Cyrius will work on the extracted bam.
