### ISSUE TITLE
RuntimeWarning: divide by zero encountered in true_divide

### ISSUE THREAD

**Issue by PavitaKae** [Illumina/Cyrius#7]
my command = python3 star_caller.py --manifest manifest.txt --genome 38 --prefix test --outDir result --threads 8
INFO:root:Processing sample HSxx at 2020-12-14 15:39:01.967956
xx/Cyrius/depth_calling/bin_count.py:84: RuntimeWarning: divide by zero encountered in true_divide
  y_counts = y_counts / np.median(y_counts)
xx/Cyrius/depth_calling/bin_count.py:84: RuntimeWarning: invalid value encountered in true_divide
  y_counts = y_counts / np.median(y_counts)
xx/envs/cyr_env/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
xx/envs/cyr_env/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
INFO:root:Processing sample HSxx at 2020-12-14 15:39:02.742290

result tsp file =
Sample	Genotype	Filter
HSxx	None	None
json file = 
{"HSxx": {"Coverage_MAD": NaN, "Median_depth": 0.0, "Total_CN": null, "Spacer_CN": null, "Total_CN_raw": null, "Spacer_CN_raw": null, "Variants_called": null, "CNV_group": null, "Genotype": null, "Filter": null, "Raw_star_allele": null, "Call_info": null, "Exon9_CN": null, "CNV_consensus": null, "d67_snp_call": null, "d67_snp_raw": null, "Variant_raw_count": null}, "HS01002_mini": {"Coverage_MAD": NaN, "Median_depth": 0.0, "Total_CN": null, "Spacer_CN": null, "Total_CN_raw": null, "Spacer_CN_raw": null, "Variants_called": null, "CNV_group": null, "Genotype": null, "Filter": null, "Raw_star_allele": null, "Call_info": null, "Exon9_CN": null, "CNV_consensus": null, "d67_snp_call": null, "d67_snp_raw": null, "Variant_raw_count": null}}
Why i cannot get result of genotype?

**Comment by xiao-chen-xc** [comment]
Hi @PavitaKae, a few things to check would be:
-Are you using a WGS bam (the whole bam, not a bamlet)?
-Does the genome build, i.e. 38, in your command line match the reference genome of your bam file?
-Is your input bam file a local one or a remote one, like one stored in Amazon s3?

**Comment by PavitaKae** [comment]
ok, i got it.
I wrong in bam file, i cut only CYP2D6 region for calculated.
when I change to WGS bam, result look ok.
How to check WGS bam? it must be all chromosome?

Thank you

**Comment by xiao-chen-xc** [comment]
You can check with the people or the paper from whom/which you got the data. 
A WGS bam should have even coverage across most of the genome.

**Comment by PavitaKae** [comment]
I found region in data folder, i check this and I got result already.
Thank you
