### ISSUE TITLE
Alignment to PGx regions only

### ISSUE THREAD

**Issue by kokyriakidis** [Illumina/Cyrius#9]
Hello,

Is there a way to align WGS fastq reads to specific regions of the reference genome? Can I somehow only map to the PGx gene regions and them use Cyrius? I want to speed up the whole process.

**Comment by xiao-chen-xc** [comment]
Hi @kokyriakidis Cyrius uses other regions of the genome to do coverage normalization. It has not been tested to work in the way you suggested, so I would suggest that you do the standard whole genome alignment.

**Comment by dridk** [comment]
I extracted CYP2D6/7 reads with a huge padding .  Cyrius doesn't success but Aldy does.
I would appreciate to have a bed file with region used by Cyrius to work. Because I can only download a subset of my genom data.

**Comment by xiao-chen-xc** [comment]
> I extracted CYP2D6/7 reads with a huge padding from a WGS . Cyrius doesn't success but Aldy does.
> I would appreciate to have a bed file with region used by Cyrius to work. Because I can only download a subset of my genom data.

Hi @dridk you can find such a bed file at https://github.com/Illumina/Cyrius/blob/master/data/CYP2D6_region_38.bed

**Comment by dridk** [comment]
Hi ! 
It works ! I extract reads from a WGS ( 148 Giga ) to a subset bam file ( 317 M ) .  And it works like a charm.... 
It means Cyrius should work on a small capture panel for NGS sequencing.

**Comment by xiao-chen-xc** [comment]
Hi @dridk 

Cyrius currently only works for WGS data. The depth normalization step assumes uniform coverage across the genome. It can be adapted to work for targeted sequencing data, but some development will be needed to add in the normalization step for targeted data.

Thanks,
Xiao
